site_name: Homelab IaC Docs
site_url: https://mafyuh.com/iac-docs
repo_url: https://github.com/Mafyuh/iac-docs
repo_name: iac-wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  logo: img/logo.png
edit_uri: edit/main/docs/